CREATE TABLE "SCHEMA_MIGRATIONS" (
"VERSION" VARCHAR2(255) NOT NULL
)

/

CREATE UNIQUE INDEX "UNIQUE_SCHEMA_MIGRATIONS" ON "SCHEMA_MIGRATIONS" ("VERSION")

/



/

CREATE TABLE "UT_LIB_DYN_QUERIES" (
"LIB_DYN_QUERY_ID" VARCHAR2(40) NOT NULL,
 "LIB_DYN_QUERY_NAME" VARCHAR2(120) NOT NULL,
 "LIB_DYN_QUERY_CLASS" VARCHAR2(120) NOT NULL,
 "LIB_DYN_QUERY" CLOB NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_LIB_DYN_QUERIES_PK PRIMARY KEY (LIB_DYN_QUERY_ID)
)

/

CREATE UNIQUE INDEX "UT_LIB_DYN_QUERIES_NAME" ON "UT_LIB_DYN_QUERIES" ("LIB_DYN_QUERY_NAME")

/

ALTER TABLE UT_LIB_DYN_QUERIES ADD CONSTRAINT UT_LIB_DYN_QUERIES_NAME UNIQUE (LIB_DYN_QUERY_NAME)

/

CREATE TABLE "UT_LIB_STARTUPS" (
"LIB_STARTUP_ID" VARCHAR2(40) NOT NULL,
 "LIB_STARTUP_NAME" VARCHAR2(120) NOT NULL,
 "LIB_STARTUP_CLASS" VARCHAR2(120) NOT NULL,
 "LIB_STARTUP" CLOB NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_LIB_STARTUPS_PK PRIMARY KEY (LIB_STARTUP_ID)
)

/

CREATE UNIQUE INDEX "UT_LIB_STARTUPS_NAME" ON "UT_LIB_STARTUPS" ("LIB_STARTUP_NAME")

/

ALTER TABLE UT_LIB_STARTUPS ADD CONSTRAINT UT_LIB_STARTUPS_NAME UNIQUE (LIB_STARTUP_NAME)

/

CREATE TABLE "UT_LIB_TEARDOWNS" (
"LIB_TEARDOWN_ID" VARCHAR2(40) NOT NULL,
 "LIB_TEARDOWN_NAME" VARCHAR2(120) NOT NULL,
 "LIB_TEARDOWN_CLASS" VARCHAR2(120) NOT NULL,
 "LIB_TEARDOWN" CLOB NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_LIB_TEARDOWNS_PK PRIMARY KEY (LIB_TEARDOWN_ID)
)

/

CREATE UNIQUE INDEX "UT_LIB_TEARDOWNS_NAME" ON "UT_LIB_TEARDOWNS" ("LIB_TEARDOWN_NAME")

/

ALTER TABLE UT_LIB_TEARDOWNS ADD CONSTRAINT UT_LIB_TEARDOWNS_NAME UNIQUE (LIB_TEARDOWN_NAME)

/

CREATE TABLE "UT_LIB_VALIDATIONS" (
"LIB_VALIDATION_ID" VARCHAR2(40) NOT NULL,
 "LIB_VALIDATION_NAME" VARCHAR2(120) NOT NULL,
 "LIB_VALIDATION_CLASS" VARCHAR2(120) NOT NULL,
 "LIB_VALIDATION" CLOB NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_LIB_VALIDATIONS_PK PRIMARY KEY (LIB_VALIDATION_ID)
)

/

CREATE UNIQUE INDEX "UT_LIB_VALIDATIONS_NAME" ON "UT_LIB_VALIDATIONS" ("LIB_VALIDATION_NAME")

/

ALTER TABLE UT_LIB_VALIDATIONS ADD CONSTRAINT UT_LIB_VALIDATIONS_NAME UNIQUE (LIB_VALIDATION_NAME)

/

CREATE TABLE "UT_LOOKUP_CATEGORIES" (
"ID" VARCHAR2(40) NOT NULL,
 "NAME" VARCHAR2(120),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_LOOKUP_CATEGORIES_PK PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "UT_LOOKUP_CATEGORIES_UK1" ON "UT_LOOKUP_CATEGORIES" ("NAME")

/

ALTER TABLE UT_LOOKUP_CATEGORIES ADD CONSTRAINT UT_LOOKUP_CATEGORIES_UK1 UNIQUE (NAME)

/

CREATE TABLE "UT_LOOKUP_DATATYPES" (
"ID" VARCHAR2(40) NOT NULL,
 "CAT_ID" VARCHAR2(40),
 "TYPE_ID" NUMBER,
 "TYPE_STRING" VARCHAR2(120),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_LOOKUP_DATATYPES_PK PRIMARY KEY (ID)
)

/

CREATE UNIQUE INDEX "UT_LOOKUP_DATATYPES_UK1" ON "UT_LOOKUP_DATATYPES" ("CAT_ID", "TYPE_STRING")

/

CREATE  INDEX "UT_LOOKUP_DTS_CAT_ID_IX" ON "UT_LOOKUP_DATATYPES" ("CAT_ID")

/

ALTER TABLE UT_LOOKUP_DATATYPES ADD CONSTRAINT UT_LOOKUP_DATATYPES_UK1 UNIQUE (CAT_ID,TYPE_STRING)

/

CREATE TABLE "UT_LOOKUP_VALUES" (
"ID" VARCHAR2(40) NOT NULL,
 "DATA_ID" VARCHAR2(40),
 "VALUE" CLOB,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_LOOKUP_VALUES_PK PRIMARY KEY (ID)
)

/

CREATE  INDEX "UT_LOOKUP_VALUES_UT_LOOKU_IX" ON "UT_LOOKUP_VALUES" ("DATA_ID")

/



/

CREATE TABLE "UT_METADATA" (
"NAME" VARCHAR2(120) NOT NULL,
 "VALUE" VARCHAR2(2000) NOT NULL,
 CONSTRAINT UT_METADATA_PK PRIMARY KEY (NAME)
)

/



/



/

CREATE TABLE "UT_STARTUPS" (
"STARTUP_ID" VARCHAR2(40) NOT NULL,
 "UT_ID" VARCHAR2(40),
 "UT_SID" VARCHAR2(40),
 "INDEX_NO" NUMBER NOT NULL,
 "STARTUP" CLOB,
 "LIB_STARTUP_ID" VARCHAR2(40),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_STARTUPS_PK PRIMARY KEY (STARTUP_ID)
)

/

CREATE  INDEX "UT_STARTUPS_LIB_VALIDN_IX" ON "UT_STARTUPS" ("LIB_STARTUP_ID")

/

CREATE  INDEX "UT_STARTUPS_SUITE_IX" ON "UT_STARTUPS" ("UT_SID")

/

CREATE  INDEX "UT_STARTUPS_TEST_IX" ON "UT_STARTUPS" ("UT_ID")

/



/

CREATE TABLE "UT_SUITE" (
"UT_SID" VARCHAR2(40) NOT NULL,
 "COVERAGE" NUMBER(1,0),
 "NAME" VARCHAR2(120) NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_SUITE_PK PRIMARY KEY (UT_SID)
)

/



/



/

CREATE TABLE "UT_SUITE_ITEMS" (
"UT_SID" VARCHAR2(40) NOT NULL,
 "UT_ID" VARCHAR2(40),
 "UT_NSID" VARCHAR2(40),
 "RUN_START" VARCHAR2(1) NOT NULL,
 "RUN_TEAR" VARCHAR2(1) NOT NULL,
 "SEQUENCE" NUMBER NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL
)

/

CREATE  INDEX "UT_SUITE_ITEMS_IX1" ON "UT_SUITE_ITEMS" ("UT_SID")

/

CREATE  INDEX "UT_SUITE_ITEMS_IX2" ON "UT_SUITE_ITEMS" ("UT_NSID")

/

CREATE  INDEX "UT_SUITE_ITEMS_IX3" ON "UT_SUITE_ITEMS" ("UT_ID")

/

CREATE UNIQUE INDEX "UT_SUITE_ITEMS_UK" ON "UT_SUITE_ITEMS" ("UT_SID", "UT_ID", "UT_NSID")

/

ALTER TABLE UT_SUITE_ITEMS ADD CONSTRAINT UT_SUITE_ITEMS_UK UNIQUE (UT_SID,UT_ID,UT_NSID)

/

CREATE TABLE "UT_SUITE_ITEM_RESULTS" (
"UTSR_ID" VARCHAR2(40) NOT NULL,
 "UTR_ID" VARCHAR2(40),
 "UTR_NSID" VARCHAR2(40),
 "SEQUENCE" NUMBER NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL
)

/

CREATE  INDEX "UT_SUITE_ITEM_RESULTS_FK1" ON "UT_SUITE_ITEM_RESULTS" ("UTSR_ID")

/

CREATE  INDEX "UT_SUITE_ITEM_RESULTS_FK2" ON "UT_SUITE_ITEM_RESULTS" ("UTR_ID")

/

CREATE  INDEX "UT_SUITE_ITEM_RESULTS_FK3" ON "UT_SUITE_ITEM_RESULTS" ("UTR_NSID")

/

CREATE UNIQUE INDEX "UT_SUITE_ITEM_RESULTS_UK" ON "UT_SUITE_ITEM_RESULTS" ("UTSR_ID", "UTR_ID", "UTR_NSID")

/

ALTER TABLE UT_SUITE_ITEM_RESULTS ADD CONSTRAINT UT_SUITE_ITEM_RESULTS_UK UNIQUE (UTSR_ID,UTR_ID,UTR_NSID)

/

CREATE TABLE "UT_SUITE_RESULTS" (
"UTSR_ID" VARCHAR2(40) NOT NULL,
 "UT_SID" VARCHAR2(40) NOT NULL,
 "NAME" VARCHAR2(120) NOT NULL,
 "STATUS" VARCHAR2(20) NOT NULL,
 "MESSAGE" VARCHAR2(2000),
 "STARTUP_STATUS" VARCHAR2(20),
 "STARTUP_MESSAGE" VARCHAR2(2000),
 "STARTUP_START_TIME" VARCHAR2(20),
 "STARTUP_END_TIME" VARCHAR2(20),
 "STARTUP_DURATION" NUMBER,
 "TEARDOWN_STATUS" VARCHAR2(20),
 "TEARDOWN_MESSAGE" VARCHAR2(2000),
 "TEARDOWN_START_TIME" VARCHAR2(20),
 "TEARDOWN_END_TIME" VARCHAR2(20),
 "TEARDOWN_DURATION" NUMBER,
 "COVERAGE" NUMBER(1,0) NOT NULL,
 "RUN_DATE" TIMESTAMP(6) NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_SUITE_RESULTS_PK PRIMARY KEY (UTSR_ID)
)

/

CREATE  INDEX "UT_SUITE_RESULTS_IX" ON "UT_SUITE_RESULTS" ("UT_SID")

/



/

CREATE TABLE "UT_TEARDOWNS" (
"TEARDOWN_ID" VARCHAR2(40) NOT NULL,
 "UT_ID" VARCHAR2(40),
 "UT_SID" VARCHAR2(40),
 "INDEX_NO" NUMBER NOT NULL,
 "TEARDOWN" CLOB,
 "LIB_TEARDOWN_ID" VARCHAR2(40),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEARDOWNS_PK PRIMARY KEY (TEARDOWN_ID)
)

/

CREATE  INDEX "UT_TEARDOWNS_LIB_VALIDN_IX" ON "UT_TEARDOWNS" ("LIB_TEARDOWN_ID")

/

CREATE  INDEX "UT_TEARDOWNS_SUITE_IX" ON "UT_TEARDOWNS" ("UT_SID")

/

CREATE  INDEX "UT_TEARDOWNS_TEST_IX" ON "UT_TEARDOWNS" ("UT_ID")

/



/

CREATE TABLE "UT_TEST" (
"UT_ID" VARCHAR2(40) NOT NULL,
 "NAME" VARCHAR2(120) NOT NULL,
 "OBJECT_NAME" VARCHAR2(120) NOT NULL,
 "OBJECT_TYPE" VARCHAR2(120) NOT NULL,
 "OBJECT_OWNER" VARCHAR2(120) NOT NULL,
 "OBJECT_CALL" VARCHAR2(120),
 "CONNECTION_NAME" VARCHAR2(120),
 "COVERAGE" NUMBER(1,0),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_PK PRIMARY KEY (UT_ID)
)

/

CREATE UNIQUE INDEX "UT_TEST_UK1" ON "UT_TEST" ("NAME")

/

ALTER TABLE UT_TEST ADD CONSTRAINT UT_TEST_UK1 UNIQUE (NAME)

/

CREATE TABLE "UT_TEST_ARGUMENTS" (
"ARG_ID" VARCHAR2(40) NOT NULL,
 "UT_ID" VARCHAR2(40),
 "OWNER" VARCHAR2(30) NOT NULL,
 "OBJECT_NAME" VARCHAR2(30),
 "PACKAGE_NAME" VARCHAR2(30),
 "OBJECT_ID" NUMBER NOT NULL,
 "OVERLOAD" VARCHAR2(40),
 "ARGUMENT_NAME" VARCHAR2(30),
 "POSITION" NUMBER NOT NULL,
 "SEQUENCE" NUMBER NOT NULL,
 "DATA_LEVEL" NUMBER NOT NULL,
 "DATA_TYPE" VARCHAR2(30),
 "DEFAULT_LENGTH" NUMBER,
 "IN_OUT" VARCHAR2(9),
 "DATA_LENGTH" NUMBER,
 "DATA_PRECISION" NUMBER,
 "DATA_SCALE" NUMBER,
 "RADIX" NUMBER,
 "CHARACTER_SET_NAME" VARCHAR2(44),
 "TYPE_OWNER" VARCHAR2(30),
 "TYPE_NAME" VARCHAR2(30),
 "TYPE_SUBNAME" VARCHAR2(30),
 "TYPE_LINK" VARCHAR2(128),
 "PLS_TYPE" VARCHAR2(30),
 "CHAR_LENGTH" NUMBER,
 "CHAR_USED" VARCHAR2(1),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_ARGUMENTS_PK PRIMARY KEY (ARG_ID)
)

/

CREATE  INDEX "UT_TEST_ARGUMENTS_IX" ON "UT_TEST_ARGUMENTS" ("UT_ID")

/



/

CREATE TABLE "UT_TEST_COVERAGE_STATS" (
"UTC_ID" VARCHAR2(40) NOT NULL,
 "UTIR_ID" VARCHAR2(40),
 "UTI_ID" VARCHAR2(40),
 "UNIT_OWNER" VARCHAR2(30),
 "UNIT_NAME" VARCHAR2(30),
 "LINE" NUMBER,
 "TOTAL_OCCUR" NUMBER,
 "TOTAL_TIME" NUMBER,
 "TEXT" VARCHAR2(4000),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_COVERAGE_STATS_PK PRIMARY KEY (UTC_ID)
)

/

CREATE  INDEX "UT_TEST_COV_STATS_UT_T_IX1" ON "UT_TEST_COVERAGE_STATS" ("UTI_ID")

/

CREATE  INDEX "UT_TEST_COV_STATS_UT_T_IX2" ON "UT_TEST_COVERAGE_STATS" ("UTIR_ID")

/



/

CREATE TABLE "UT_TEST_IMPL" (
"UTI_ID" VARCHAR2(40) NOT NULL,
 "UT_ID" VARCHAR2(40) NOT NULL,
 "NAME" VARCHAR2(120) NOT NULL,
 "EXPECTED_RETURN" VARCHAR2(20),
 "EXPECTED_RETURN_ERROR" VARCHAR2(200),
 "DYNAMIC_VALUE_QUERY" CLOB,
 "LIB_DYN_QUERY_ID" VARCHAR2(40),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_IMPL_PK PRIMARY KEY (UTI_ID)
)

/

CREATE UNIQUE INDEX "UT_TEST_IMPL_UK1" ON "UT_TEST_IMPL" ("UT_ID", "NAME")

/

CREATE  INDEX "UT_TEST_IMPL_UT_TEST_IX" ON "UT_TEST_IMPL" ("UT_ID")

/

CREATE  INDEX "UT_TEST_LIB_DYN_QUERIES_IX" ON "UT_TEST_IMPL" ("LIB_DYN_QUERY_ID")

/

ALTER TABLE UT_TEST_IMPL ADD CONSTRAINT UT_TEST_IMPL_UK1 UNIQUE (UT_ID,NAME)

/

CREATE TABLE "UT_TEST_IMPL_ARGUMENTS" (
"UTI_ID" VARCHAR2(40) NOT NULL,
 "ARG_ID" VARCHAR2(40) NOT NULL,
 "INPUT_VALUE" CLOB,
 "OUTPUT_VALUE" CLOB,
 "TEST_OUTVAL" NUMBER(1,0) DEFAULT 1  NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_IMPL_ARGUMENTS_PK PRIMARY KEY (UTI_ID,ARG_ID)
)

/

CREATE  INDEX "UT_TEST_IMPL_ARGUMENTS_UT_IX1" ON "UT_TEST_IMPL_ARGUMENTS" ("ARG_ID")

/

CREATE  INDEX "UT_TEST_IMPL_ARGUMENTS_UT_IX2" ON "UT_TEST_IMPL_ARGUMENTS" ("UTI_ID")

/



/

CREATE TABLE "UT_TEST_IMPL_ARG_RESULTS" (
"UTIAR_ID" VARCHAR2(40) NOT NULL,
 "UTIR_ID" VARCHAR2(40),
 "UTI_ID" VARCHAR2(40) NOT NULL,
 "ARG_ID" VARCHAR2(40) NOT NULL,
 "NAME" VARCHAR2(120),
 "STATUS" VARCHAR2(20) NOT NULL,
 "MESSAGE" VARCHAR2(2000),
 "RUN_DATE" TIMESTAMP(6) NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_IMPL_ARG_RESULTS_PK PRIMARY KEY (UTIAR_ID)
)

/

CREATE  INDEX "UT_TEST_IMPL_ARG_RESULTS_IX1" ON "UT_TEST_IMPL_ARG_RESULTS" ("UTI_ID")

/

CREATE  INDEX "UT_TEST_IMPL_ARG_RESULTS_IX2" ON "UT_TEST_IMPL_ARG_RESULTS" ("ARG_ID")

/

CREATE  INDEX "UT_TEST_IMPL_ARG_RESULTS_IX3" ON "UT_TEST_IMPL_ARG_RESULTS" ("UTIR_ID")

/



/

CREATE TABLE "UT_TEST_IMPL_RESULTS" (
"UTIR_ID" VARCHAR2(40) NOT NULL,
 "UTI_ID" VARCHAR2(40) NOT NULL,
 "UTR_ID" VARCHAR2(40) NOT NULL,
 "NAME" VARCHAR2(120) NOT NULL,
 "STATUS" VARCHAR2(20) NOT NULL,
 "MESSAGE" VARCHAR2(2000),
 "START_TIME" VARCHAR2(20),
 "END_TIME" VARCHAR2(20),
 "DURATION" NUMBER,
 "STARTUP_STATUS" VARCHAR2(20),
 "STARTUP_MESSAGE" VARCHAR2(2000),
 "STARTUP_START_TIME" VARCHAR2(20),
 "STARTUP_END_TIME" VARCHAR2(20),
 "STARTUP_DURATION" NUMBER,
 "OP_CALL_STATUS" VARCHAR2(20),
 "OP_CALL_MESSAGE" VARCHAR2(2000),
 "OP_CALL_START_TIME" VARCHAR2(20),
 "OP_CALL_END_TIME" VARCHAR2(20),
 "OP_CALL_DURATION" NUMBER,
 "TEARDOWN_STATUS" VARCHAR2(20),
 "TEARDOWN_MESSAGE" VARCHAR2(2000),
 "TEARDOWN_START_TIME" VARCHAR2(20),
 "TEARDOWN_END_TIME" VARCHAR2(20),
 "TEARDOWN_DURATION" NUMBER,
 "RUN_DATE" TIMESTAMP(6) NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_IMPL_RESULTS_PK PRIMARY KEY (UTIR_ID)
)

/

CREATE  INDEX "UT_TEST_IMPL_RESULTS_UT_T_IX1" ON "UT_TEST_IMPL_RESULTS" ("UTI_ID")

/

CREATE  INDEX "UT_TEST_IMPL_RESULTS_UT_T_IX2" ON "UT_TEST_IMPL_RESULTS" ("UTR_ID")

/



/

CREATE TABLE "UT_TEST_IMPL_VAL_RESULTS" (
"UTIVR_ID" VARCHAR2(40) NOT NULL,
 "UTIR_ID" VARCHAR2(40),
 "UTI_ID" VARCHAR2(40) NOT NULL,
 "VAL_ID" VARCHAR2(40) NOT NULL,
 "VAL_TYPE" VARCHAR2(40) NOT NULL,
 "STATUS" VARCHAR2(20) NOT NULL,
 "MESSAGE" VARCHAR2(2000),
 "VAL_START_TIME" VARCHAR2(20),
 "VAL_END_TIME" VARCHAR2(20),
 "VAL_DURATION" NUMBER,
 "RUN_DATE" TIMESTAMP(6),
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_IMPL_VAL_RES_PK PRIMARY KEY (UTIVR_ID)
)

/

CREATE  INDEX "UT_TEST_IMPL_VAL_RES_IX1" ON "UT_TEST_IMPL_VAL_RESULTS" ("VAL_ID")

/

CREATE  INDEX "UT_TEST_IMPL_VAL_RES_IX2" ON "UT_TEST_IMPL_VAL_RESULTS" ("UTI_ID")

/

CREATE  INDEX "UT_TEST_IMPL_VAL_RES_IX3" ON "UT_TEST_IMPL_VAL_RESULTS" ("UTIR_ID")

/



/

CREATE TABLE "UT_TEST_RESULTS" (
"UTR_ID" VARCHAR2(40) NOT NULL,
 "UT_ID" VARCHAR2(40) NOT NULL,
 "NAME" VARCHAR2(120) NOT NULL,
 "STATUS" VARCHAR2(20) NOT NULL,
 "MESSAGE" VARCHAR2(2000),
 "COVERAGE" NUMBER(1,0) NOT NULL,
 "TEST_USER_NAME" VARCHAR2(120),
 "CONNECTION_NAME" VARCHAR2(120),
 "RUN_DATE" TIMESTAMP(6) NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_TEST_RESULTS_PK PRIMARY KEY (UTR_ID)
)

/

CREATE  INDEX "UT_TEST_RESULTS_UT_TEST_IX1" ON "UT_TEST_RESULTS" ("UT_ID")

/



/

CREATE TABLE "UT_VALIDATIONS" (
"VALIDATION_ID" VARCHAR2(40) NOT NULL,
 "UTI_ID" VARCHAR2(40) NOT NULL,
 "INDEX_NO" NUMBER NOT NULL,
 "VALIDATION" CLOB,
 "LIB_VALIDATION_ID" VARCHAR2(40),
 "APPLY_VALIDATION" NUMBER(1,0) DEFAULT 1  NOT NULL,
 "CREATED_ON" TIMESTAMP(6) NOT NULL,
 "CREATED_BY" VARCHAR2(120) NOT NULL,
 "UPDATED_ON" TIMESTAMP(6) NOT NULL,
 "UPDATED_BY" VARCHAR2(120) NOT NULL,
 CONSTRAINT UT_VALIDATIONS_PK PRIMARY KEY (VALIDATION_ID)
)

/

CREATE  INDEX "UT_VALIDATIONS_LIB_VALIDN_IX" ON "UT_VALIDATIONS" ("LIB_VALIDATION_ID")

/

CREATE  INDEX "UT_VALIDATIONS_TEST_IMPL_IX" ON "UT_VALIDATIONS" ("UTI_ID")

/



/

ALTER TABLE "UT_LOOKUP_DATATYPES" ADD CONSTRAINT "UT_LOOKUP_DATATYPES_UT_LO_FK1" FOREIGN KEY ("CAT_ID") REFERENCES "UT_LOOKUP_CATEGORIES"("ID") ON DELETE CASCADE

/

ALTER TABLE "UT_LOOKUP_VALUES" ADD CONSTRAINT "UT_LOOKUP_VALUES_UT_LOOKU_FK1" FOREIGN KEY ("DATA_ID") REFERENCES "UT_LOOKUP_DATATYPES"("ID") ON DELETE CASCADE

/

ALTER TABLE "UT_STARTUPS" ADD CONSTRAINT "UT_STARTUPS_LIB_VALIDN_FK1" FOREIGN KEY ("LIB_STARTUP_ID") REFERENCES "UT_LIB_STARTUPS"("LIB_STARTUP_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_STARTUPS" ADD CONSTRAINT "UT_STARTUPS_SUITE_FK1" FOREIGN KEY ("UT_SID") REFERENCES "UT_SUITE"("UT_SID") ON DELETE CASCADE

/

ALTER TABLE "UT_STARTUPS" ADD CONSTRAINT "UT_STARTUPS_TEST_FK1" FOREIGN KEY ("UT_ID") REFERENCES "UT_TEST"("UT_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_SUITE_ITEMS" ADD CONSTRAINT "UT_SUITE_ITEMS_FK1" FOREIGN KEY ("UT_SID") REFERENCES "UT_SUITE"("UT_SID") ON DELETE CASCADE

/

ALTER TABLE "UT_SUITE_ITEMS" ADD CONSTRAINT "UT_SUITE_ITEMS_FK2" FOREIGN KEY ("UT_ID") REFERENCES "UT_TEST"("UT_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_SUITE_ITEMS" ADD CONSTRAINT "UT_SUITE_ITEMS_FK3" FOREIGN KEY ("UT_NSID") REFERENCES "UT_SUITE"("UT_SID") ON DELETE CASCADE

/

ALTER TABLE "UT_SUITE_ITEM_RESULTS" ADD CONSTRAINT "UT_SUITE_ITEM_RESULTS_FK1" FOREIGN KEY ("UTSR_ID") REFERENCES "UT_SUITE_RESULTS"("UTSR_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_SUITE_ITEM_RESULTS" ADD CONSTRAINT "UT_SUITE_ITEM_RESULTS_FK2" FOREIGN KEY ("UTR_ID") REFERENCES "UT_TEST_RESULTS"("UTR_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_SUITE_ITEM_RESULTS" ADD CONSTRAINT "UT_SUITE_ITEM_RESULTS_FK3" FOREIGN KEY ("UTR_NSID") REFERENCES "UT_SUITE_RESULTS"("UTSR_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_SUITE_RESULTS" ADD CONSTRAINT "UT_SUITE_RESULTS_FK1" FOREIGN KEY ("UT_SID") REFERENCES "UT_SUITE"("UT_SID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEARDOWNS" ADD CONSTRAINT "UT_TEARDOWNS_LIB_VALIDN_FK1" FOREIGN KEY ("LIB_TEARDOWN_ID") REFERENCES "UT_LIB_TEARDOWNS"("LIB_TEARDOWN_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEARDOWNS" ADD CONSTRAINT "UT_TEARDOWNS_SUITE_FK1" FOREIGN KEY ("UT_SID") REFERENCES "UT_SUITE"("UT_SID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEARDOWNS" ADD CONSTRAINT "UT_TEARDOWNS_TEST_FK1" FOREIGN KEY ("UT_ID") REFERENCES "UT_TEST"("UT_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_ARGUMENTS" ADD CONSTRAINT "UT_TEST_ARGUMENTS_FK" FOREIGN KEY ("UT_ID") REFERENCES "UT_TEST"("UT_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_COVERAGE_STATS" ADD CONSTRAINT "UT_TEST_COV_STATS_UT_T_FK1" FOREIGN KEY ("UTI_ID") REFERENCES "UT_TEST_IMPL"("UTI_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_COVERAGE_STATS" ADD CONSTRAINT "UT_TEST_COV_STATS_UT_T_FK2" FOREIGN KEY ("UTIR_ID") REFERENCES "UT_TEST_IMPL_RESULTS"("UTIR_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL" ADD CONSTRAINT "UT_TEST_IMPL_UT_TEST_FK1" FOREIGN KEY ("UT_ID") REFERENCES "UT_TEST"("UT_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL" ADD CONSTRAINT "UT_TEST_LIB_DYN_QUERIES_FK1" FOREIGN KEY ("LIB_DYN_QUERY_ID") REFERENCES "UT_LIB_DYN_QUERIES"("LIB_DYN_QUERY_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_ARGUMENTS" ADD CONSTRAINT "UT_TEST_IMPL_ARGUMENTS_UT_FK1" FOREIGN KEY ("ARG_ID") REFERENCES "UT_TEST_ARGUMENTS"("ARG_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_ARGUMENTS" ADD CONSTRAINT "UT_TEST_IMPL_ARGUMENTS_UT_FK2" FOREIGN KEY ("UTI_ID") REFERENCES "UT_TEST_IMPL"("UTI_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_ARG_RESULTS" ADD CONSTRAINT "UT_TEST_IMPL_ARG_RESULTS__FK1" FOREIGN KEY ("UTI_ID") REFERENCES "UT_TEST_IMPL"("UTI_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_ARG_RESULTS" ADD CONSTRAINT "UT_TEST_IMPL_ARG_RESULTS__FK2" FOREIGN KEY ("ARG_ID") REFERENCES "UT_TEST_ARGUMENTS"("ARG_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_RESULTS" ADD CONSTRAINT "UT_TEST_IMPL_RESULTS_UT_T_FK1" FOREIGN KEY ("UTI_ID") REFERENCES "UT_TEST_IMPL"("UTI_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_RESULTS" ADD CONSTRAINT "UT_TEST_IMPL_RESULTS_UT_T_FK2" FOREIGN KEY ("UTR_ID") REFERENCES "UT_TEST_RESULTS"("UTR_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_VAL_RESULTS" ADD CONSTRAINT "UT_TEST_IMPL_VAL_RES_FK1" FOREIGN KEY ("VAL_ID") REFERENCES "UT_VALIDATIONS"("VALIDATION_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_VAL_RESULTS" ADD CONSTRAINT "UT_TEST_IMPL_VAL_RES_FK2" FOREIGN KEY ("UTI_ID") REFERENCES "UT_TEST_IMPL"("UTI_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_IMPL_VAL_RESULTS" ADD CONSTRAINT "UT_TEST_IMPL_VAL_RES_FK3" FOREIGN KEY ("UTIR_ID") REFERENCES "UT_TEST_IMPL_RESULTS"("UTIR_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_TEST_RESULTS" ADD CONSTRAINT "UT_TEST_RESULTS_UT_TEST_FK1" FOREIGN KEY ("UT_ID") REFERENCES "UT_TEST"("UT_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_VALIDATIONS" ADD CONSTRAINT "UT_VALIDATIONS_LIB_VALIDN_FK1" FOREIGN KEY ("LIB_VALIDATION_ID") REFERENCES "UT_LIB_VALIDATIONS"("LIB_VALIDATION_ID") ON DELETE CASCADE

/

ALTER TABLE "UT_VALIDATIONS" ADD CONSTRAINT "UT_VALIDATIONS_TEST_IMPL_FK1" FOREIGN KEY ("UTI_ID") REFERENCES "UT_TEST_IMPL"("UTI_ID") ON DELETE CASCADE

/

