source 'https://rubygems.org'

gem 'rails', '7.1.3.2'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 6.0.0'
  gem 'coffee-rails', '~> 5.0.0'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# Oracle
gem 'activerecord-oracle_enhanced-adapter', '~> 1.4.0'
gem 'ruby-oci8', '~> 2.1.0'
gem 'ruby-plsql', '~> 0.5.0'
